-- Run this in Supabase SQL Editor.
-- The publishable key belongs in Vercel/Android runtime configuration, never here.

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  full_name text,
  role text not null default 'operator' check (role in ('owner', 'admin', 'operator', 'viewer')),
  created_at timestamptz not null default now()
);

create table if not exists public.device_registry (
  device_id text primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  vehicle_id text,
  label text,
  app_version text,
  status text not null default 'offline',
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.device_registry enable row level security;

drop policy if exists "profiles_self_read" on public.profiles;
create policy "profiles_self_read" on public.profiles for select to authenticated using (user_id = auth.uid());

drop policy if exists "profiles_self_update" on public.profiles;
create policy "profiles_self_update" on public.profiles for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "device_registry_authenticated_read" on public.device_registry;
create policy "device_registry_authenticated_read" on public.device_registry for select to authenticated using (
  organization_id in (select organization_id from public.profiles where user_id = auth.uid())
);

drop policy if exists "device_registry_authenticated_write" on public.device_registry;
create policy "device_registry_authenticated_write" on public.device_registry for all to authenticated using (
  organization_id in (select organization_id from public.profiles where user_id = auth.uid())
) with check (
  organization_id in (select organization_id from public.profiles where user_id = auth.uid())
);

create table if not exists public.gps_locations (
  id bigint generated by default as identity primary key,
  device_id text not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  speed double precision not null default 0,
  accuracy double precision,
  altitude double precision,
  bearing double precision,
  timestamp timestamptz not null default now()
);

create index if not exists gps_locations_device_timestamp_idx
  on public.gps_locations (device_id, timestamp desc);

alter table public.gps_locations enable row level security;

drop policy if exists "gps_locations_public_read" on public.gps_locations;
drop policy if exists "gps_locations_public_insert" on public.gps_locations;

-- El APK envia posiciones como 'anon' (no tiene login). La lectura queda
-- restringida a usuarios autenticados del panel.
create policy "gps_locations_authenticated_read"
  on public.gps_locations for select
  to authenticated
  using (true);

create policy "gps_locations_public_insert"
  on public.gps_locations for insert
  to anon, authenticated
  with check (true);

-- Required by Supabase Realtime for INSERT events.
alter table public.gps_locations replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'gps_locations'
  ) then
    alter publication supabase_realtime add table public.gps_locations;
  end if;
end $$;

create table if not exists public.vehicle_commands (
  id bigint generated by default as identity primary key,
  vehicle_id text not null,
  command text not null check (command in ('activate', 'stop', 'immobilize')),
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.vehicle_commands enable row level security;

-- Las acciones de control requieren sesion autenticada en el panel.
drop policy if exists "vehicle_commands_authenticated_insert" on public.vehicle_commands;
create policy "vehicle_commands_authenticated_insert"
  on public.vehicle_commands for insert
  to authenticated
  with check (true);

drop policy if exists "vehicle_commands_authenticated_read" on public.vehicle_commands;
create policy "vehicle_commands_authenticated_read"
  on public.vehicle_commands for select
  to authenticated
  using (true);

create table if not exists public.devices (
  id text primary key,
  status text not null default 'offline',
  last_seen timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.devices add column if not exists platform text;
alter table public.devices add column if not exists model text;
alter table public.devices add column if not exists app_version text;
alter table public.devices add column if not exists battery smallint;

alter table public.devices enable row level security;

drop policy if exists "devices_public_read" on public.devices;
drop policy if exists "devices_public_insert" on public.devices;
drop policy if exists "devices_public_update" on public.devices;

-- El lector del panel necesita sesion; el APK (sin login) escribe con 'anon'.
create policy "devices_authenticated_read"
  on public.devices for select
  to authenticated
  using (true);

create policy "devices_public_insert"
  on public.devices for insert
  to anon, authenticated
  with check (true);

create policy "devices_public_update"
  on public.devices for update
  to anon, authenticated
  using (true)
  with check (true);

alter table public.devices replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'devices'
  ) then
    alter publication supabase_realtime add table public.devices;
  end if;
end $$;

-- =====================================================================
-- Flota de vehiculos (categoria "Motos" del panel)
-- =====================================================================

create table if not exists public.vehicles (
  id text primary key,
  device_id text,
  name text not null,
  plate text,
  driver text,
  status text not null default 'offline',
  speed double precision not null default 0,
  battery smallint not null default 0,
  fuel smallint,
  temp double precision,
  odometer text,
  location text,
  route jsonb,
  last_update timestamptz not null default now()
);

alter table public.vehicles enable row level security;

-- Todo el manejo de la flota es del panel autenticado.
drop policy if exists "vehicles_authenticated_all" on public.vehicles;
create policy "vehicles_authenticated_all"
  on public.vehicles for all
  to authenticated
  using (true)
  with check (true);

-- =====================================================================
-- Alertas
-- =====================================================================

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  severity text not null default 'info' check (severity in ('critical', 'warning', 'info')),
  title text not null,
  description text,
  vehicle_id text,
  plate text,
  speed double precision not null default 0,
  battery smallint,
  voltage double precision,
  location_name text,
  lat double precision,
  lng double precision,
  read boolean not null default false,
  timestamp timestamptz not null default now()
);

alter table public.alerts enable row level security;

drop policy if exists "alerts_authenticated_all" on public.alerts;
create policy "alerts_authenticated_all"
  on public.alerts for all
  to authenticated
  using (true)
  with check (true);

create index if not exists alerts_timestamp_idx on public.alerts (timestamp desc);

-- =====================================================================
-- Geocercas
-- =====================================================================

create table if not exists public.geofences (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'circle' check (type in ('circle', 'polygon')),
  center numeric[],
  positions jsonb,
  radius double precision not null default 600,
  color text not null default '#00E676',
  rule text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.geofences enable row level security;

drop policy if exists "geofences_authenticated_all" on public.geofences;
create policy "geofences_authenticated_all"
  on public.geofences for all
  to authenticated
  using (true)
  with check (true);

-- =====================================================================
-- Login por dispositivo (multitenant)
-- Cada dispositivo puede tener una cuenta Auth propia. Al instalar el APK,
-- una Edge Function (service_role) crea el usuario Auth del dispositivo y
-- guarda su auth_user_id en devices. El operador (fila en profiles) puede
-- ver toda la flota; el dispositivo autenticado solo ve su propia data.
-- =====================================================================

alter table public.devices add column if not exists auth_user_id uuid references auth.users(id) on delete cascade;
create unique index if not exists devices_auth_user_id_idx
  on public.devices (auth_user_id)
  where auth_user_id is not null;

-- True si el usuario actual es un operador del panel (tiene fila en profiles).
-- security definer: evita recursion con las politicas de la misma tabla.
create or replace function public.is_operator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p where p.user_id = auth.uid()
  );
$$;

-- Dispositivos: el operador ve toda la flota; el dispositivo solo su fila.
drop policy if exists "devices_authenticated_read" on public.devices;
create policy "devices_authenticated_read"
  on public.devices for select
  to authenticated
  using (public.is_operator() or auth_user_id = auth.uid());

-- Ubicaciones: el operador ve todo; el dispositivo solo las suyas.
drop policy if exists "gps_locations_authenticated_read" on public.gps_locations;
create policy "gps_locations_authenticated_read"
  on public.gps_locations for select
  to authenticated
  using (
    public.is_operator()
    or exists (
      select 1 from public.devices d
      where d.id = public.gps_locations.device_id
        and d.auth_user_id = auth.uid()
    )
  );

-- Flota, alertas, geocercas y comandos: solo operador (el dispositivo no
-- debe leer ni controlar datos que no son de su dispositivo).
drop policy if exists "vehicles_authenticated_all" on public.vehicles;
create policy "vehicles_authenticated_all"
  on public.vehicles for all
  to authenticated
  using (public.is_operator())
  with check (public.is_operator());

drop policy if exists "alerts_authenticated_all" on public.alerts;
create policy "alerts_authenticated_all"
  on public.alerts for all
  to authenticated
  using (public.is_operator())
  with check (public.is_operator());

drop policy if exists "geofences_authenticated_all" on public.geofences;
create policy "geofences_authenticated_all"
  on public.geofences for all
  to authenticated
  using (public.is_operator())
  with check (public.is_operator());

drop policy if exists "vehicle_commands_authenticated_insert" on public.vehicle_commands;
create policy "vehicle_commands_authenticated_insert"
  on public.vehicle_commands for insert
  to authenticated
  with check (public.is_operator());

drop policy if exists "vehicle_commands_authenticated_read" on public.vehicle_commands;
create policy "vehicle_commands_authenticated_read"
  on public.vehicle_commands for select
  to authenticated
  using (public.is_operator());
